# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4f3e66450abfaf305486581a024bdbcd915c12a86bfe23a19d1f6ee76c2f2aa25efe4668094235c896610cf85353a78d7e8c13ba93998610173f56a94e84815

test:
  secret_key_base: fb9d1266f3a9d05504786730e40dfc2b2d68464d2a2da610e2a2a77c205eedd2db94f01d30e16a1af17d3ea8b4e22d5f4748c4d1f8e7ec10c9d4855521422843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
